### ISSUE TITLE
cmsis

### ISSUE THREAD

**Issue by KJA000** [KJA000/000#9]
jiaekim@raspberry:~/CMSIS-NN $ ./Tests/UnitTest/unittest_targets.py 
Traceback (most recent call last):
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 490, in <module>
    sys.exit(test_targets(args))
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 323, in test_targets
    detect_targets(targets)
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 67, in detect_targets
    process = subprocess.Popen(['mbedls'],
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mbedls'

**Comment by KJA000** [comment]
jiaekim@raspberry:~/CMSIS-NN $ ./Tests/UnitTest/unittest_targets.py 
Traceback (most recent call last):
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 490, in <module>
    sys.exit(test_targets(args))
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 323, in test_targets
    detect_targets(targets)
  File "/home/jiaekim/CMSIS-NN/./Tests/UnitTest/unittest_targets.py", line 67, in detect_targets
    process = subprocess.Popen(['mbedls'],
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mbedls'

**Comment by KJA000** [comment]
Error: RETURN CODE ERROR:mbedls.lstools_linux:Could not get serial devices by id. This could be because your Linux distribution does not use udev, or does not create /dev/serial/by-id symlinks. Please submit an issue to github.com/armmbed/mbed-ls.
